replicaCount: 1

image:
  repository: flux159/mcp-server-kubernetes
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# service account to manage permissions of the MCP server
serviceAccount:
  annotations: {}
  # your created service account name bound to the respective cluster role
  name: "mcp"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

readOnlyTools: false

port: 3000

# adjust as needed depending on the size of the cluster. This is 5MB, which is usually sufficient for large clusters.
spawnMaxBuffer: "5242880"

# base64 encoded kubeconfig YAML file.
kubecfg: ""
