name: cd

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          # Start minikube with additional flags to support kubectl cp
          minikube start --driver=docker --extra-config=apiserver.enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
          minikube status

          # Enable necessary addons
          minikube addons enable default-storageclass
          minikube addons enable storage-provisioner

      - name: Configure kubectl for Minikube
        run: |
          # Get the minikube IP and configure kubectl
          MINIKUBE_IP=$(minikube ip)
          echo "Minikube IP: $MINIKUBE_IP"

          # Update kubeconfig to use the correct server URL
          kubectl config set-cluster minikube --server=https://$MINIKUBE_IP:8443 --insecure-skip-tls-verify=true

          # Verify connection
          kubectl cluster-info
          kubectl get nodes

      - name: Run Tests in Minikube
        run: bun run test

      - name: Clean up kubectl proxy
        if: always()
        run: |
          if [ -n "$KUBECTL_PROXY_PID" ]; then
            echo "Stopping kubectl proxy (PID: $KUBECTL_PROXY_PID)"
            kill $KUBECTL_PROXY_PID || true
          fi

          # Restore the original kubeconfig (optional)
          sed -i 's|http://localhost:8080|https://192.168.49.2:8443|g' ~/.kube/config

      - name: Update version number
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit the new version
        run: |
          # Make sure we're on main branch
          git checkout main

          # Update the version in package.json and manifest.json and commit the change
          jq --arg v "${{ steps.version.outputs.current-version }}" '.version = $v' package.json > temp.json && mv temp.json package.json
          jq --arg v "${{ steps.version.outputs.current-version }}" '.version = $v' manifest.json > temp.json && mv temp.json manifest.json
          sed -i "s/^version: .*/version: ${{ steps.version.outputs.current-version }}/" CITATION.cff

          git add package.json manifest.json CITATION.cff
          git commit -m "Bump version to ${{ steps.version.outputs.current-version }}"

          # Create and push the tag
          git tag ${{ steps.version.outputs.current-version }}

          # Push both the commit and the tag
          git push origin main
          git push origin ${{ steps.version.outputs.current-version }}

      - name: Build For production
        run: bun run build

      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          echo "//registry.npmjs.org/:always-auth=true" >> ~/.npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build dxt
        run: |
          bun run builddxt

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload v${{ steps.version.outputs.current-version }} mcp-server-kubernetes.dxt --clobber

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: flux159/${{ github.event.repository.name }}:latest,flux159/${{ github.event.repository.name }}:v${{ steps.version.outputs.current-version }}
